"""Documentation tests (T401-T407).

These lock down the threat model and production-architecture ADRs as living
artifacts. T406 in particular enforces that every LLM-specific threat in the
threat model has a corresponding adversarial eval or is explicitly marked as
having no automated coverage — turning the document into a CI-checked contract
rather than aspirational prose.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
THREAT_MODEL_PATH = REPO_ROOT / "docs" / "THREAT_MODEL.md"
ADR_PROD_PATH = REPO_ROOT / "docs" / "adr" / "013-production-architecture.md"
ADR_TM_METHOD_PATH = REPO_ROOT / "docs" / "adr" / "014-threat-model-methodology.md"
EVALS_PATH = REPO_ROOT / "evals" / "dataset" / "traces.jsonl"

REQUIRED_TM_HEADINGS = (
    "## Section 1: Scope and assumptions",
    "## Section 2: STRIDE — by component",
    "## Section 3: LLM-specific threats",
    "## Section 4: Adversarial coverage",
    "## Section 5: Compliance posture",
    "## Section 6: Threat-to-mitigation traceability",
)

REQUIRED_ADR_HEADINGS = (
    "## Status",
    "## Context",
    "## Decision",
    "## Rationale",
    "## Consequences",
    "## Alternatives",
)

# Production architecture ADR must enumerate these layer headings.
REQUIRED_PROD_LAYERS = (
    "Identity",
    "Data",
    "Observability",
    "Reliability",
    "LLM",
    "Deployment",
)

FORBIDDEN_STRINGS = (
    "Co-Authored-By",
    "Signed-off-by",
    "Generated by",
    "AI-assisted",
    "with help from",
    "ChatGPT",
    "Copilot",
)


@pytest.fixture(scope="module")
def threat_model_text() -> str:
    return THREAT_MODEL_PATH.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def eval_dataset_text() -> str:
    return EVALS_PATH.read_text(encoding="utf-8")


# ---------- T401 ----------
def test_t401_threat_model_exists_and_nonempty() -> None:
    assert THREAT_MODEL_PATH.exists(), "docs/THREAT_MODEL.md is missing"
    assert THREAT_MODEL_PATH.stat().st_size > 1000, (
        "docs/THREAT_MODEL.md is suspiciously short; the document should be substantial"
    )


# ---------- T402 ----------
def test_t402_threat_model_has_required_sections(threat_model_text: str) -> None:
    for heading in REQUIRED_TM_HEADINGS:
        assert heading in threat_model_text, f"missing section heading: {heading!r}"


# ---------- T403 ----------
def test_t403_adr_013_production_architecture_exists_with_required_sections() -> None:
    assert ADR_PROD_PATH.exists(), f"missing: {ADR_PROD_PATH}"
    text = ADR_PROD_PATH.read_text(encoding="utf-8")
    for heading in REQUIRED_ADR_HEADINGS:
        assert heading in text, f"ADR-013 missing heading: {heading!r}"


# ---------- T404 ----------
def test_t404_adr_014_threat_model_methodology_exists_with_required_sections() -> None:
    assert ADR_TM_METHOD_PATH.exists(), f"missing: {ADR_TM_METHOD_PATH}"
    text = ADR_TM_METHOD_PATH.read_text(encoding="utf-8")
    for heading in REQUIRED_ADR_HEADINGS:
        assert heading in text, f"ADR-014 missing heading: {heading!r}"


# ---------- T405 ----------
def test_t405_threat_model_has_no_forbidden_strings(threat_model_text: str) -> None:
    for fs in FORBIDDEN_STRINGS:
        assert fs not in threat_model_text, (
            f"forbidden string {fs!r} appears in THREAT_MODEL.md"
        )


# ---------- T406 ----------
SECTION3_RE = re.compile(
    r"^## Section 3:.*?(?=^## Section 4:)", re.DOTALL | re.MULTILINE
)
SECTION4_RE = re.compile(
    r"^## Section 4:.*?(?=^## Section 5:)", re.DOTALL | re.MULTILINE
)
THREAT_ID_RE = re.compile(r"\bTM-LLM-\d{3}\b")
EV_REF_RE = re.compile(r"\bEV\d{3}\b")


def test_t406_every_llm_threat_has_eval_or_no_coverage_marker(
    threat_model_text: str, eval_dataset_text: str
) -> None:
    section3_match = SECTION3_RE.search(threat_model_text)
    assert section3_match, "Section 3 not found"
    section3 = section3_match.group()

    section4_match = SECTION4_RE.search(threat_model_text)
    assert section4_match, "Section 4 not found"
    section4 = section4_match.group()

    threat_ids = sorted(set(THREAT_ID_RE.findall(section3)))
    assert threat_ids, "expected at least one TM-LLM-NNN id in Section 3"

    referenced_evs: set[str] = set()
    for tid in threat_ids:
        matching_lines = [
            line for line in section4.splitlines() if tid in line
        ]
        assert matching_lines, (
            f"threat {tid} appears in Section 3 but has no row in Section 4"
        )
        line = matching_lines[0]
        ev_matches = EV_REF_RE.findall(line)
        has_no_cov = "no automated coverage" in line.lower()
        assert ev_matches or has_no_cov, (
            f"threat {tid} in Section 4 must reference an EV-NNN trace or the "
            "literal phrase 'no automated coverage'"
        )
        referenced_evs.update(ev_matches)

    # Every referenced EV must actually exist in the dataset.
    dataset_ids = set(re.findall(r'"id":\s*"(EV\d{3})"', eval_dataset_text))
    missing = referenced_evs - dataset_ids
    assert not missing, (
        f"Section 4 references EV traces that do not exist in evals/dataset/traces.jsonl: "
        f"{sorted(missing)}"
    )


# ---------- T407 ----------
def test_t407_adr_013_lists_required_production_layers() -> None:
    text = ADR_PROD_PATH.read_text(encoding="utf-8")
    for layer in REQUIRED_PROD_LAYERS:
        assert layer in text, f"ADR-013 missing required layer: {layer!r}"


# ---------- bonus: dataset is parseable JSON ----------
def test_eval_dataset_remains_parseable(eval_dataset_text: str) -> None:
    """Belt-and-braces: any change to the dataset must keep it as valid JSONL."""
    for line in eval_dataset_text.splitlines():
        if not line.strip():
            continue
        json.loads(line)
